### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by byngj123** [moedje/kodi-repo-gaymods#1]
This may be a stupid question, but how do I install this into Kodi?
There could do with being instructions in the readme file as I have found several forums containing a link to this repo but no one seems to be able to add it.

**Comment by moedje** [comment]
The repository doesn't work for some reason it's the first repo I tried to create but the adding themselves can be installed via the zip files so just download the individual zips and install in Kodi that way. The most complete addon I have done was plugin.video.hubgay there is a zip of it in my GitHub page GitHub.com/Moedje

Thanks for your interest mate most of them are just works in progress but I still find them more helpful than trying to use the Str8 ones

I welcome anyone to help sort out the repo I just don't know what I haven't done to make it work directly in Kodi so I instead have to use it via the zip files

**Comment by darthrothgar** [comment]
How would I install this an amazon fire stick running kodi?

**Comment by moedje** [comment]
I have never tested any of them on a fire stick and no idea how you download or upload a zip file to a fire stick sorry I can't help. If I can sort out getting the repo to correctly work without zips then I would imagine it would work but I don't know how to make it work correctly it just gives me errors but the individual adding install ok by zip file so not experienced enough at repos to know what's wrong

Anyone that knows what has gone wrong with the repo or how to fix it please feel free to pull or let me know what I have done wrong. Was using a python script to create the addons zips and repo?

**Comment by moedje** [comment]
[repository.kodi-repo-gaymods-1.6.9.zip](https://github.com/moedje/kodi-repo-gaymods/files/671462/repository.kodi-repo-gaymods-1.6.9.zip)

This has fixed the problems with Kodi being unable to install and update the addons from the repository directly. Please update the installed Repo and you will be able to simply select the addons you wish to install from inside Kodi's install from Repository part of the Addon's screen.

- Features the latest update to plugin.video.hubGAY with an API based display of most of the HUB traffic sites with a setting to be able to switch between gay or straight content, global categories accross all the sites, and a global search. Also includes a basic Motherless section and the Porky Tube website has been included. Version 0.9.5 also includes a test of the new Tumblr Video's section which at the moment only features a single Tumblr blog but soon this will allow viewing Tumblr video's off any Tumblr blogs you save. It loads 10 pages at a time for a quick experience. This is the first test and has limited functionality and some bugs be patient.

Again upgrade the REPO to version 1.6.9 and problems with installing addons will be fixed. Hope everyone enjoys.
