### ISSUE TITLE
Version mismatch for plugin.video.hubgay

### ISSUE THREAD

**Issue by RogueScholar** [moedje/kodi-repo-gaymods#3]
Forgive me if I'm making an obvious misjudgment, but I believe when you recently updated the repo, you listed a version of the hubgay plugin which has yet to be released. For the last two weeks Kodi has been reporting a failure to update plugin.video.hubgay to version 1.3.2, but encounters a 404 error when trying to retrieve the plugin.video.hubgay-1.3.2.zip file.

**Comment by moedje** [comment]
Hopefully this should be fixed now as Plugin.Video.Hubgay has been updated to v1.3.3 to fix an issue with Fire Stick and the module script.module.urlquick so I can confirm that all the files are there so hopefully this updates ok now.

Hope to make some fixes for some of the sites no longer working someday soon.
